### ISSUE TITLE
Bad reference to /bootstrap-sass

### ISSUE THREAD

**Issue by bakgaard** [cutterbl/ui-grid-sass#1]
I have an issue when attempting to use ``_main.scss``.
Line 2 says:

```@import "bootstrap-sass/assets/stylesheets/bootstrap/variables";```

But it should most likely be the following, since it does not include ``bootstrap-sass``:

```@import "../../bootstrap-sass/assets/stylesheets/bootstrap/variables";```

**Comment by cutterbl** [comment]
Most likely you are missing an `includePaths` option, pointing to your node_modules, in the settings for whichever SASS compiler you are using. This is referenced in the README file.
